### ISSUE TITLE
Can you cut a release?

### ISSUE THREAD

**Issue by blaggacao** [blyxyas/mdbook-emojicodes#1]
:smile: :pray: 

I'd like to package this for `nixpkgs`.

**Comment by blyxyas** [comment]
What is *cutting a release*? #2 Was merged and the package updated to `0.1.3`, is this solved?

**Comment by blaggacao** [comment]
Ah, sry, "make a release tag" for it. That wasn't clear.

For context: various tooling in `nixpkgs`, including the auto-updater feed on release tags.

**Comment by blyxyas** [comment]
Does the release need to have a binary file attached to it?

**Comment by blaggacao** [comment]
No. Fortunately, `nix` (through the `nixpkgs` infrastructure) will build everything _reproducibly_ from sources.

**Comment by blyxyas** [comment]
A new release can be found at https://github.com/blyxyas/mdbook-emojicodes/releases/tag/0.1.3

**Comment by blaggacao** [comment]
Wonderful!

![image](https://user-images.githubusercontent.com/7548295/216656799-07e88fbc-b9be-4d15-b872-8f9018d2489c.png)

https://github.com/NixOS/nixpkgs/pull/214300 has it, now! :rocket:
