### ISSUE TITLE
Feature Request: custom emoji

### ISSUE THREAD

**Issue by savbran** [blyxyas/mdbook-emojicodes#4]
Hi, I'm wondering if it's possible to use custom emojis for example contained in a folder at the same level of the md file to convert.

For example, if the containing folder's name is: custom_icons and you have in it some svg emojis like urgent.svg, in the markdown document could be used the emoji shortcode **:custom_icons_urgent:** (i.e. the shortcode could be composed by the folder name and the image name).

Do you think it's a good idea?

**Comment by blyxyas** [comment]
I could see it being implemented. Im currently a little bit busy, so it will take some days / weeks. If you want to implement it yourself, I'll gladly accept it.

**Comment by savbran** [comment]
@blyxyas thanks for your answer. I'm not a Rust expert but I'm learning it. Considering this is an interesting feature, take you time no problem. Meanwhile I'll try to clone your repository and give a look, trying to understand how the "crate content" works :) ... regards.

**Comment by blyxyas** [comment]
Ok I implemented it. Let me know if this is what you mean

![image](https://user-images.githubusercontent.com/73757586/221044073-243ad5a3-0b40-4fc7-9935-f5cffad9bc84.png)

```
# Chapter 1

:my_svg:
```

![image](https://user-images.githubusercontent.com/73757586/221044134-18a14080-ab1b-4086-9025-ee5cf7b62ca6.png)

**Comment by blyxyas** [comment]
Ok I implemented it:

Now you can have a `my_svg.svg`  in the directory `src/custom_emojis` and use it like any other emoji.

![image](https://user-images.githubusercontent.com/73757586/221045594-3ebd2b0e-4216-4405-80c1-d520fb8e1508.png)

```markdown
# Chapter 1

:my_svg:
```

![image](https://user-images.githubusercontent.com/73757586/221045630-9b853a57-7f8f-4aa9-8b42-cba3e768367e.png)

**Comment by blyxyas** [comment]
@savbran let me know if this is what you meant, the size obviously depends on the size of your vector graphic

**Comment by savbran** [comment]
@blyxyas did you push the update on the master branch? I ask because I can't see any recent change.
Anyway, the size should be the one of emojis, like on this text row with the emojis: 🐞 😃
If you push the update I can try... many thanks!

**Comment by blyxyas** [comment]
@savbran This feature has been successfully implemented and available in version *0.2.1*. Let me know if you need anything.
