### ISSUE TITLE
Updating `Nixpkgs`

### ISSUE THREAD

**Issue by blyxyas** [blyxyas/mdbook-emojicodes#6]
The nixpkgs distribution of this crate is in version `0.1.3`, very outdated. It should be updated.
@blaggacao, wanna give this a try?

**Comment by blaggacao** [comment]
I think it was the strange version composition that prevented automated updates. It _should_ :crossed_fingers: auto-update in the future upon a new Release Tag here in Github.

https://github.com/NixOS/nixpkgs/pull/249580

**Comment by blyxyas** [comment]
Thanks! :heart:
