### ISSUE TITLE
Request: Binary releases on github for use with `cargo-binstall`

### ISSUE THREAD

**Issue by mirrorcult** [blyxyas/mdbook-emojicodes#9]
hello! we [currently use](https://github.com/space-wizards/docs) `mdbook-emojicodes` for a documentation site, with deployments handled by github actions. we install the necessary `mdbook` plugins using https://github.com/taiki-e/install-action, which under the hood uses https://github.com/cargo-bins/cargo-binstall, which just downloads binaries from github releases. 

other preprocessors like https://github.com/tommilligan/mdbook-admonish do have binaries for x86 linux in their releases, so the action runner is generally pretty quick. with this preprocessor included, deploy times go from ~10s to ~1m20s, which isn't unmanageable or anything, but it would be very nice if binary releases on tagged versions could be included so the workflow is even faster here

**Comment by blyxyas** [comment]
I just created [the release for 0.3.0](https://github.com/blyxyas/mdbook-emojicodes/releases/tag/0.3.0), they have binaries optimized for size. I hope that's what you need :cat: (Don't hesitate to say it if it isn't what you need)

**Comment by mirrorcult** [comment]
yep, this works for us!
